a=int(input("enter a value"))
print(a)
b=int(input("enter b value"))
print(b)
print("addition of",a,"&",b)
print(a+b)
print("subtraction of",a,"&",b)
print(a-b)
print("multiplication of",a, "&",b)
print(a*b)
print("division of",a, "&",b)
print(a/b)
